const images = {

  //Login Assets
  visual: require('../Assets/Login/visual.png'),
  loginLogo: require('../Assets/Login/loginLogo.png'),
  passwordVisible: require('../Assets/Login/passwordVisible.png'),

  // Dashboard Assets
  logo: require('../Assets/Dashboard/logo.png'),
  notification: require('../Assets/Dashboard/notification.png'),
  userPic: require('../Assets/Dashboard/userPic.png'),
  members: require('../Assets/Dashboard/members.png'),
  task: require('../Assets/Dashboard/task.png'),
  message: require('../Assets/Dashboard/message.png'),
  project: require('../Assets/Dashboard/project.png'),
  project1: require('../Assets/Dashboard/project1.png'),
  project2: require('../Assets/Dashboard/project2.png'),
  folder: require('../Assets/Dashboard/folder.png'),
  memberPerson: require('../Assets/Dashboard/memberPerson.png'),
  workIcon: require('../Assets/Dashboard/workIcon.png'),
  dashboadIcon: require('../Assets/Dashboard/dashboadIcon.png'),
  plus: require('../Assets/Dashboard/plus.png'),
  loaderLogo: require('../Assets/Dashboard/loaderLogo.png'),
  reports: require('../Assets/Dashboard/reports.png'),

  // Projects Assets
  filter: require('../Assets/Projects/filter.png'),
  search: require('../Assets/Projects/search.png'),
  popChat: require('../Assets/Projects/popChat.png'),
  popProject: require('../Assets/Projects/popProject.png'),
  popTask: require('../Assets/Projects/popTask.png'),
  closeIcon: require('../Assets/Projects/closeIcon.png'),
  reject: require('../Assets/Projects/reject.png'),
  accept: require('../Assets/Projects/accept.png'),
  checked: require('../Assets/Projects/checked.png'),
  emptyChecked: require('../Assets/Projects/emptyChecked.png'),

  // Profile Assets
  logOut: require('../Assets/Profile/logOut.png'),
  rightArrow: require('../Assets/Profile/rightArrow.png'),
  Setting: require('../Assets/Profile/Setting.png'),
  contacts: require('../Assets/Profile/contacts.png'),
  write: require('../Assets/Profile/write.png'),
  leftArrow: require('../Assets/Profile/leftArrow.png'),
  gallery: require('../Assets/Profile/gallery.png'),
  pin: require('../Assets/Profile/pin.png'),
  filledPin: require('../Assets/Profile/filledPin.png'),
  Decline: require('../Assets/Profile/Decline.png'),
  Photo: require('../Assets/Profile/Photo.png'),
  circle: require('../Assets/Profile/circle.png'),
  circleFilled: require('../Assets/Profile/circleFilled.png'),


  // Chat Assets
  favourite: require('../Assets/Chat/favourite.png'),
  iconPlus: require('../Assets/Chat/iconPlus.png'),
  emptyFavourite: require('../Assets/Chat/emptyFavourite.png'),
  close: require('../Assets/Chat/close.png'),
  dropDown: require('../Assets/Chat/dropDown.png'),
  charUserpic1: require('../Assets/Chat/charUserpic1.png'),
  charUserpic2: require('../Assets/Chat/charUserpic2.png'),
  charUserpic3: require('../Assets/Chat/charUserpic3.png'),
  charUserpic4: require('../Assets/Chat/charUserpic4.png'),
  charUserpic5: require('../Assets/Chat/charUserpic5.png'),
  menu: require('../Assets/Chat/menu.png'),
  media1: require('../Assets/Chat/media1.png'),
  media2: require('../Assets/Chat/media2.png'),
  media3: require('../Assets/Chat/media3.png'),
  mic: require('../Assets/Chat/mic.png'),
  Nudge: require('../Assets/Chat/Nudge.png'),
  fileUpload: require('../Assets/Chat/fileUpload.png'),
  emoji: require('../Assets/Chat/emoji.png'),
  camera: require('../Assets/Chat/camera.png'),
  document: require('../Assets/Chat/document.png'),
  Delete: require('../Assets/Chat/Delete.png'),
  invite: require('../Assets/Chat/invite.png'),
  Contacts: require('../Assets/Chat/Contacts.png'),
  unreadMessage: require('../Assets/Chat/unreadMessage.png'),
  volume: require('../Assets/Chat/volume.png'),
  fillFavourite: require('../Assets/Chat/fillFavourite.png'),
  replyMessage: require('../Assets/Chat/replyMessage.png'),
  forwardMessage: require('../Assets/Chat/forwardMessage.png'),
  addTask: require('../Assets/Chat/addTask.png'),
  Download: require('../Assets/Chat/Download.png'),
  calender: require('../Assets/Chat/calender.png'),
  setAdmin: require('../Assets/Chat/setAdmin.png'),
  closeMedia: require('../Assets/Chat/closeMedia.png'),
  Send: require('../Assets/Chat/Send.png'),


  // Reports
  report_download: require('../Assets/Reports/report_download.png'),
  location: require('../Assets/Reports/location.png'),
  checkBox: require('../Assets/Reports/checkBox.png'),
  checkBoxFill: require('../Assets/Reports/checkBoxFill.png'),

};
export default images;